### ISSUE TITLE
utop-eval-phrase executes next phrase instead of current one

### ISSUE THREAD

**Issue by ysalmon** [ocaml-community/utop#329] opened 2020-06-07 10:33 UTC
Hello,

I am just starting to use utop and its Emacs minor mode with Tuareg.

I found out that, except when at the end of the buffer, when ``utop-eval-phrase``is invoked from the end of a line, it will execute the phrase on the next line instead of the phrase on the current line.

For a (ridiculous) example whith [*] representing the cursor :
```ocaml
let _ = 4 [*]

let _ = 3
```
This breaks the pattern where I (or my students) will insert a phrase (eg. a type declaration) in front of already existing code and want to execute it after having typed it.

I had a similar problem at some point with Tuareg itself https://github.com/ocaml/tuareg/issues/158 but currently tuareg 2.2.0 from opam executes the first line.

**Comment by leungbk** [comment] 2021-03-04 17:53
I wrote https://github.com/ocaml-community/utop/pull/346 since `utop-eval-phrase` wasn't working at all for me. I tried executing your example and it seems to work in the way that you want; can you confirm @ysalmon?

**Comment by leungbk** [comment] 2021-03-04 18:04
Oh, seems to be a Tuareg issue. When I use the OPAM release 2.2.0 of Tuareg, the problem you describe exists, but if you use the latest Melpa rev along with my patch, the behavior is as you want it to be.

**Comment by bbatsov** [comment] 2022-07-21 09:33
@ysalmon @leungbk I can't reproduce this issue with the latest `utop.el` from MELPA.

**Comment by bbatsov** [comment] 2022-07-21 09:34
(seems this was fixed by #346 and can be closed)

**Closed** 2022-07-21 09:50 UTC
Labels: emacs
